service_params:
  env: dev
  secret_key: 36080001349340267925113477454910
server_params:
  http_port: :8080
clients_params:
  event_client_address: event-service:9091
  auth_client_address: auth-service:9092
  user_client_address: user-service:9093
